### ISSUE TITLE
Extension - Try rewrite in `rust`

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/lambda-dispatch#69]
## Motivations
- The extension within the Lambda is the most performance sensitive: it's using CPU that the Lambda could use to perform tasks
- The 400% CPU usage of dotnet due to inefficient workers looking for work is having a negative impact on performance
- A simple demo showed that Node.js can be pinned at 110% CPU with Rust at < 30% CPU for sending the requests

## To-Do
- [x] Create debug feature in Router to allow an extension to connect and have its LambdaInstance lazily created
- [x] Write a demo to confirm that duplex recv/send works on HTTP2 requests for Rust/hyper
- [x] Handle GET requests without Lambda Invoke (use debug feature above)
- [x] Run a performance comparison
- [x] Implement POST requests
- [x] Gracefully handle errors
   - This is mostly complete
- [x] Implement duplex requests for caller requests (or new ticket)
- [x] Degenerate case of `/ping` with 1 channel from Router to Extension but 10 concurrent requests into the Router from `oha`, is running at 1/4 to 1/3rd the speed of the dotnet extension (e.g. 1k to 1.3k RPS vs 3k RPS)
   - This is fixed in #84 

## Results

| Test Case           | oha `-c` | Channels<br>Router &lt;--&gt; Extension | Rust RPS | Rust CPU | Rust Node.js CPU | DotNet RPS | DotNet CPU | DotNet Node.js CPU | Direct Node.js RPS | Direct Node.js CPU
| ------------------- | -------: | --------------------------------------: | -------: |-------: | -------: | -------: | ---------: | -------: | ---------: | -------: |
| `/ping`             |       10 |                                      10 |   19,007 |   90% | 113% |   14,652 | 330-350% | 95% | 20,035 | 115% |
| `/ping`             |       10 |                                       1 |    4,934 |      27% |   36% |  3,603 |      115% | 30% | ^^^ | ^^^ |
| `/ping`             |       1 |                                       10 |    4,997 |      29% |  37% |  3,451 |     111% | 27%| 15,975  | 97% |
| `/echo` 9.3 MB      |       10 |                                       1 |       81 |      76% |  113%  |     N/A |      N/A | N/A | 228 | 179% |
| `/echo-slow` 9.3 MB |       10 |                                       1 |       54 |      52% | 150% |       51 |     154% | 147% | 117 | 158% |
| `/echo-slow` 9.3 MB |        1 |                                       1 |       54 |     52% |   150%  |    50 |      152% |  150% | 96 | 215% |

### After - `/ping` - 10 Concurrent Requests - 10 Channels from Router to Extension

✅ Extension CPU is ~80-90% (vs Node.js at 113% or dotnet extension at ~350%) - note that the extension is doing 2x more work than Node.js in this case (it's receiving and proxying the request and response while Node.js is only receiving the request and immediately writing back a static response - this is the worst case scenario where the contained app is using no CPU at all and only shuffling requests).

Note: Tokio set to current thread

```log
oha -c 10 -z 10s http://localhost:5001/ping
Summary:
  Success rate: 100.00%
  Total:        10.0009 secs
  Slowest:      0.0047 secs
  Fastest:      0.0002 secs
  Average:      0.0005 secs
  Requests/sec: 19007.2403

  Total data:   742.54 KiB
  Size/request: 4 B
  Size/sec:     74.25 KiB

Response time histogram:
  0.000 [1]      |
  0.001 [165746] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.001 [19340]  |■■■
  0.002 [2468]   |
  0.002 [1803]   |
  0.002 [511]    |
  0.003 [182]    |
  0.003 [19]     |
  0.004 [7]      |
  0.004 [8]      |
  0.005 [5]      |

Response time distribution:
  10.00% in 0.0004 secs
  25.00% in 0.0004 secs
  50.00% in 0.0005 secs
  75.00% in 0.0006 secs
  90.00% in 0.0006 secs
  95.00% in 0.0007 secs
  99.00% in 0.0016 secs
  99.90% in 0.0025 secs
  99.99% in 0.0034 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0019 secs, 0.0014 secs, 0.0022 secs
  DNS-lookup:   0.0005 secs, 0.0004 secs, 0.0006 secs

Status code distribution:
  [200] 190090 responses
```

### After - `/ping` - 10 Concurrent Requests - 1 Channel from Router to Extension

✅ Extension CPU is ~27% with current thread Tokio runtime config

```log
oha -c 10 -z 10s http://localhost:5001/ping
Summary:
  Success rate: 100.00%
  Total:        10.0005 secs
  Slowest:      0.0212 secs
  Fastest:      0.0013 secs
  Average:      0.0020 secs
  Requests/sec: 4934.2600

  Total data:   192.75 KiB
  Size/request: 4 B
  Size/sec:     19.27 KiB

Response time histogram:
  0.001 [1]     |
  0.003 [46522] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.005 [882]   |
  0.007 [557]   |
  0.009 [530]   |
  0.011 [580]   |
  0.013 [239]   |
  0.015 [12]    |
  0.017 [9]     |
  0.019 [0]     |
  0.021 [13]    |

Response time distribution:
  10.00% in 0.0016 secs
  25.00% in 0.0016 secs
  50.00% in 0.0017 secs
  75.00% in 0.0017 secs
  90.00% in 0.0020 secs
  95.00% in 0.0039 secs
  99.00% in 0.0105 secs
  99.90% in 0.0126 secs
  99.99% in 0.0199 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0008 secs, 0.0006 secs, 0.0010 secs
  DNS-lookup:   0.0002 secs, 0.0001 secs, 0.0003 secs

Status code distribution:
  [200] 49345 responses
```

### After - `/echo` - 10 Concurrent Requests - 1 Channel from Router to Extension

Note: `/echo` sends/receives in duplex while `/echo-slow` is all that has been implemented in the dotnet Extension; this is not the fault of dotnet (as the Router handles duplex) it's just that this was not built in the Extension.  This is provided for reference as an upper bound on the throughput of the Rust extension.

```log
oha -c 10 -z 10s -m POST -T application/octet-stream -D ./oha http://localhost:5001/echo    
Summary:
  Success rate: 100.00%
  Total:        10.0018 secs
  Slowest:      0.1470 secs
  Fastest:      0.0319 secs
  Average:      0.1215 secs
  Requests/sec: 81.7855

  Total data:   7.44 GiB
  Size/request: 9.32 MiB
  Size/sec:     762.18 MiB

Response time histogram:
  0.032 [1]   |
  0.043 [0]   |
  0.055 [1]   |
  0.066 [1]   |
  0.078 [1]   |
  0.089 [1]   |
  0.101 [1]   |
  0.112 [1]   |
  0.124 [731] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.135 [79]  |■■■
  0.147 [1]   |

Response time distribution:
  10.00% in 0.1201 secs
  25.00% in 0.1208 secs
  50.00% in 0.1217 secs
  75.00% in 0.1226 secs
  90.00% in 0.1239 secs
  95.00% in 0.1247 secs
  99.00% in 0.1285 secs
  99.90% in 0.1470 secs
  99.99% in 0.1470 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0021 secs, 0.0017 secs, 0.0023 secs
  DNS-lookup:   0.0009 secs, 0.0008 secs, 0.0009 secs

Status code distribution:
  [200] 818 responses
```

### After - `/echo-slow` - 10 Concurrent Requests - 1 Channel from Router to Extension

```log
oha -c 10 -z 10s -m POST -T application/octet-stream -D ./oha http://localhost:5001/echo-slow
Summary:
  Success rate: 100.00%
  Total:        10.0004 secs
  Slowest:      0.2075 secs
  Fastest:      0.0421 secs
  Average:      0.1833 secs
  Requests/sec: 53.9977

  Total data:   4.91 GiB
  Size/request: 9.32 MiB
  Size/sec:     503.22 MiB

Response time histogram:
  0.042 [1]   |
  0.059 [0]   |
  0.075 [1]   |
  0.092 [1]   |
  0.108 [1]   |
  0.125 [1]   |
  0.141 [1]   |
  0.158 [1]   |
  0.174 [1]   |
  0.191 [491] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.208 [41]  |■■

Response time distribution:
  10.00% in 0.1808 secs
  25.00% in 0.1817 secs
  50.00% in 0.1828 secs
  75.00% in 0.1853 secs
  90.00% in 0.1899 secs
  95.00% in 0.1944 secs
  99.00% in 0.2033 secs
  99.90% in 0.2075 secs
  99.99% in 0.2075 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0017 secs, 0.0012 secs, 0.0021 secs
  DNS-lookup:   0.0005 secs, 0.0004 secs, 0.0006 secs

Status code distribution:
  [200] 540 responses
```

### After - `/echo-slow` - 1 Concurrent Requests - 1 Channel from Router to Extension

```log
oha -c 1 -z 10s -m POST -T application/octet-stream -D ./oha http://localhost:5001/echo-slow 
Summary:
  Success rate: 100.00%
  Total:        10.0002 secs
  Slowest:      0.0319 secs
  Fastest:      0.0170 secs
  Average:      0.0184 secs
  Requests/sec: 54.2988

  Total data:   4.94 GiB
  Size/request: 9.32 MiB
  Size/sec:     506.02 MiB

Response time histogram:
  0.017 [1]   |
  0.018 [393] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.020 [117] |■■■■■■■■■
  0.021 [14]  |■
  0.023 [6]   |
  0.024 [4]   |
  0.026 [3]   |
  0.027 [2]   |
  0.029 [0]   |
  0.030 [0]   |
  0.032 [3]   |

Response time distribution:
  10.00% in 0.0175 secs
  25.00% in 0.0177 secs
  50.00% in 0.0180 secs
  75.00% in 0.0185 secs
  90.00% in 0.0193 secs
  95.00% in 0.0201 secs
  99.00% in 0.0258 secs
  99.90% in 0.0319 secs
  99.99% in 0.0319 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0007 secs, 0.0007 secs, 0.0007 secs
  DNS-lookup:   0.0002 secs, 0.0002 secs, 0.0002 secs

Status code distribution:
  [200] 543 responses
```

### Before - `/ping` - 10 Concurrent Requests - 10 Channels from Router to Extension

🔴 Extension CPU is 330-350% (vs Node.js at 97%)

```log
oha -c 10 -z 10s http://localhost:5001/ping 
Summary:
  Success rate: 100.00%
  Total:        10.0006 secs
  Slowest:      0.0984 secs
  Fastest:      0.0002 secs
  Average:      0.0007 secs
  Requests/sec: 14652.3652

  Total data:   572.39 KiB
  Size/request: 4 B
  Size/sec:     57.24 KiB

Response time histogram:
  0.000 [1]      |
  0.010 [146522] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.020 [0]      |
  0.030 [0]      |
  0.039 [0]      |
  0.049 [0]      |
  0.059 [0]      |
  0.069 [0]      |
  0.079 [0]      |
  0.089 [0]      |
  0.098 [10]     |

Response time distribution:
  10.00% in 0.0004 secs
  25.00% in 0.0005 secs
  50.00% in 0.0005 secs
  75.00% in 0.0007 secs
  90.00% in 0.0009 secs
  95.00% in 0.0013 secs
  99.00% in 0.0037 secs
  99.90% in 0.0045 secs
  99.99% in 0.0079 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0019 secs, 0.0017 secs, 0.0021 secs
  DNS-lookup:   0.0009 secs, 0.0008 secs, 0.0010 secs

Status code distribution:
  [200] 146533 responses
```

### Before - `/ping` - 10 Concurrent Requests - 1 Channel from Router to Extension

🔴 Extension CPU is ~90%

```log
oha -c 10 -z 10s http://localhost:5001/ping
Summary:
  Success rate: 100.00%
  Total:        10.0008 secs
  Slowest:      0.0257 secs
  Fastest:      0.0017 secs
  Average:      0.0028 secs
  Requests/sec: 3603.8977

  Total data:   140.79 KiB
  Size/request: 4 B
  Size/sec:     14.08 KiB

Response time histogram:
  0.002 [1]     |
  0.004 [34294] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.006 [1463]  |■
  0.009 [152]   |
  0.011 [66]    |
  0.014 [53]    |
  0.016 [3]     |
  0.018 [0]     |
  0.021 [2]     |
  0.023 [2]     |
  0.026 [6]     |

Response time distribution:
  10.00% in 0.0022 secs
  25.00% in 0.0023 secs
  50.00% in 0.0025 secs
  75.00% in 0.0030 secs
  90.00% in 0.0035 secs
  95.00% in 0.0040 secs
  99.00% in 0.0062 secs
  99.90% in 0.0121 secs
  99.99% in 0.0251 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0014 secs, 0.0011 secs, 0.0018 secs
  DNS-lookup:   0.0005 secs, 0.0003 secs, 0.0007 secs

Status code distribution:
  [200] 36042 responses
```

### Before - `/echo-slow` - 10 Concurrent Requests - 1 Channel from Router to Extension

```log
oha -c 10 -z 10s -m POST -T application/octet-stream -D ./oha http://localhost:5001/echo-slow
Summary:
  Success rate: 100.00%
  Total:        10.0009 secs
  Slowest:      0.2978 secs
  Fastest:      0.1180 secs
  Average:      0.1925 secs
  Requests/sec: 51.3954

  Total data:   4.68 GiB
  Size/request: 9.32 MiB
  Size/sec:     478.97 MiB

Response time histogram:
  0.118 [1]   |
  0.136 [0]   |
  0.154 [1]   |
  0.172 [1]   |
  0.190 [250] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.208 [234] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.226 [16]  |■■
  0.244 [8]   |■
  0.262 [1]   |
  0.280 [1]   |
  0.298 [1]   |

Response time distribution:
  10.00% in 0.1875 secs
  25.00% in 0.1886 secs
  50.00% in 0.1900 secs
  75.00% in 0.1934 secs
  90.00% in 0.1981 secs
  95.00% in 0.2112 secs
  99.00% in 0.2340 secs
  99.90% in 0.2978 secs
  99.99% in 0.2978 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0017 secs, 0.0012 secs, 0.0023 secs
  DNS-lookup:   0.0005 secs, 0.0003 secs, 0.0006 secs

Status code distribution:
  [200] 514 responses
```

### Before - `/echo-slow` - 1 Concurrent Request - 1 Channel from Router to Extension

```log
oha -c 1 -z 10s -m POST -T application/octet-stream -D ./oha http://localhost:5001/echo-slow
Summary:
  Success rate: 100.00%
  Total:        10.0006 secs
  Slowest:      0.0773 secs
  Fastest:      0.0175 secs
  Average:      0.0193 secs
  Requests/sec: 51.6968

  Total data:   4.71 GiB
  Size/request: 9.32 MiB
  Size/sec:     481.78 MiB

Response time histogram:
  0.017 [1]   |
  0.023 [502] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.029 [8]   |
  0.035 [4]   |
  0.041 [1]   |
  0.047 [0]   |
  0.053 [0]   |
  0.059 [0]   |
  0.065 [0]   |
  0.071 [0]   |
  0.077 [1]   |

Response time distribution:
  10.00% in 0.0182 secs
  25.00% in 0.0185 secs
  50.00% in 0.0188 secs
  75.00% in 0.0193 secs
  90.00% in 0.0199 secs
  95.00% in 0.0210 secs
  99.00% in 0.0299 secs
  99.90% in 0.0773 secs
  99.99% in 0.0773 secs


Details (average, fastest, slowest):
  DNS+dialup:   0.0005 secs, 0.0005 secs, 0.0005 secs
  DNS-lookup:   0.0001 secs, 0.0001 secs, 0.0001 secs

Status code distribution:
  [200] 517 responses
```

**Comment by huntharo** [comment]
With the current_thread tokio runtime, CPU usage of the new extension is ~60-70% with Node.js at 110% CPU.  This is a substantial reduction.

When deployed on Lambda, the tokio runtime is creating only 1-2 threads by default, so this is not a problem there (it's primarily a problem on high-core-count machines like a Mac M2 Max).
