### ISSUE TITLE
Router / Extension - Hanging on `/echo` duplex POST request/response on Lambda (throttling?)

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/lambda-dispatch#88]
## Motivations
- Only happens when deployed to Lambda
- At 45 seconds, when the extension gracefully exits, a few requests either get stuck or are already stuck and cause the Lambda to timeout at 60 seconds
- The Lambda does not return from the invoke so it cannot be immediately replaced

## To-Do
- [ ] Add unit tests for the extension
- [ ] Add units tests for the router
- [ ] Try testing with Docker or Raspberry Pi to shift the timing around in an attempt to trigger the problem locally

**Comment by huntharo** [comment]
This is probably also due to RAM being less than 1,769 MB, but this should be tested to confirm that there is no hidden bug.
