### ISSUE TITLE
Router - Start Lambda while prior Lambda is stopping

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/lambda-dispatch#89]
## Motivations
- True graceful shutdown means we are going to be waiting up to, say, a minute for some longer-lived Lambdas to complete all of their in-flight requests when it is time to shutdown
- This means that the Router will be down 1 instance for up to 1 minute for each Lambda that shuts down during a given 1 minute period
- This is VERY noticeable with small quantities of Lambdas
- This shows up as 5 second delays on requests in the best case when 2 of 2 Lambdas both gracefully exit at the same time
- Starting another Lambda while the prior Lambda is still stopping will:
   - Init a few more execution environments which will be helpful during traffic bursts
   - Allow RPS rates to remain steady when invokes are being rotated

## To-Do
- [x] Every time a Lambda is invoked, invoke 2 with 1 set to "init-only"?
- [x] Return after init for the lambda marked as init-only
- [x] If the lambda is already init'd, return immediately
- [x] Do not count the init-only lambda as a starting or running instance
- [x] Drop the closing lambda from the lambda invoke count as soon as the close initiates
