### ISSUE TITLE
Minimize the size of the LambdaLB image

### ISSUE THREAD

**Issue by huntharo** [pwrdrvr/lambda-dispatch#9]
## Motivations
- We want this as small as possible
- "Make it look like Rust" 🤣 

## ToDo
- [x] Remove the accidentally copied in non-Native AoT files from the router build (update `.dockerignore`) (100+ MB)
- [x] Remove the `libicu` files (about 40 MB)
- [x] Test and confirm this works
